In [1]:
import pandas as pd

In [9]:
df = pd.read_csv("movies.csv",index_col="Title")
df

                              Rank           Studio       Gross  Year
Title
Avengers: Endgame                1      Buena Vista  $2,796.30   2019
Avatar                           2              Fox  $2,789.70   2009
Titanic                          3        Paramount  $2,187.50   1997
Star Wars: The Force Awakens     4      Buena Vista  $2,068.20   2015
Avengers: Infinity War           5      Buena Vista  $2,048.40   2018
...                            ...              ...         ...   ...
Yogi Bear                      778  Warner Brothers    $201.60   2010
Garfield: The Movie            779              Fox    $200.80   2004
Cats & Dogs                    780  Warner Brothers    $200.70   2001
The Hunt for Red October       781        Paramount    $200.50   1990
Valkyrie                       782              MGM    $200.30   2008

[782 rows x 4 columns]

In [10]:
df.head()

                              Rank       Studio       Gross  Year
Title
Avengers: Endgame                1  Buena Vista  $2,796.30   2019
Avatar                           2          Fox  $2,789.70   2009
Titanic                          3    Paramount  $2,187.50   1997
Star Wars: The Force Awakens     4  Buena Vista  $2,068.20   2015
Avengers: Infinity War           5  Buena Vista  $2,048.40   2018

In [17]:
df.sort_index()

                                Rank           Studio       Gross  Year
Title
10,000 B.C.                      536  Warner Brothers    $269.80   2008
101 Dalmatians                   708      Buena Vista    $215.90   1961
101 Dalmatians                   425      Buena Vista    $320.70   1996
2 Fast 2 Furious                 632        Universal    $236.40   2003
2012                              93             Sony    $769.70   2009
...                              ...              ...         ...   ...
Yogi Bear                        778  Warner Brothers    $201.60   2010
You've Got Mail                  582  Warner Brothers    $250.80   1998
Your Name.                       356              FUN    $358.00   2017
Zootopia                          37      Buena Vista  $1,023.80   2016
xXx: The Return of Xander Cage   385        Paramount    $346.10   2017

[782 rows x 4 columns]

In [18]:
df["Studio"].value_counts().head(10)

Studio
Warner Brothers    132
Buena Vista        125
Fox                117
Universal          109
Sony                86
Paramount           76
Dreamworks          27
Lionsgate           21
New Line            16
MGM                 11
Name: count, dtype: int64

In [22]:
df[(df["Studio"]=="Warner Brothers") & (df["Year"] == 2018)]

,Rank,Studio,Gross,Year
Title,,,,
Aquaman,21,Warner Brothers,"$1,148.00",2018
Fantastic Beasts: The Crimes of Grindelwald,129,Warner Brothers,$653.80,2018
Ready Player One,161,Warner Brothers,$582.90,2018
Detective Chinatown 2,178,Warner Brothers,$544.10,2018
The Meg,188,Warner Brothers,$530.20,2018
A Star is Born,256,Warner Brothers,$434.90,2018
Rampage,262,Warner Brothers,$428.00,2018
The Nun,339,Warner Brothers,$365.60,2018
Ocean's 8,477,Warner Brothers,$297.70,2018
Tomb Raider,523,Warner Brothers,$274.70,2018
Crazy Rich Asians,625,Warner Brothers,$238.50,2018
Paddington 2,663,Warner Brothers,$227.30,2018
Smallfoot,717,Warner Brothers,$214.10,2018

In [25]:
df[df["Studio"].str.lower().str.contains("uni")]

                                Rank     Studio       Gross  Year
Title
Jurassic World                     6  Universal  $1,671.70   2015
Furious 7                          8  Universal  $1,516.00   2015
Jurassic World: Fallen Kingdom    13  Universal  $1,309.50   2018
The Fate of the Furious           17  Universal  $1,236.00   2017
Minions                           19  Universal  $1,159.40   2015
...                              ...        ...         ...   ...
The Break-Up                     763  Universal    $205.00   2006
Everest                          766  Universal    $203.40   2015
Patch Adams                      772  Universal    $202.30   1998
Kindergarten Cop                 775  Universal    $202.00   1990
Straight Outta Compton           776  Universal    $201.60   2015

[109 rows x 4 columns]

In [ ]:
df["Gross" ]=df["Gross"].str.replace("$","").str.replace(",","").astype(float)

                              Rank           Studio   Gross  Year
Title
Avengers: Endgame                1      Buena Vista  2796.3  2019
Avatar                           2              Fox  2789.7  2009
Titanic                          3        Paramount  2187.5  1997
Star Wars: The Force Awakens     4      Buena Vista  2068.2  2015
Avengers: Infinity War           5      Buena Vista  2048.4  2018
...                            ...              ...     ...   ...
Yogi Bear                      778  Warner Brothers   201.6  2010
Garfield: The Movie            779              Fox   200.8  2004
Cats & Dogs                    780  Warner Brothers   200.7  2001
The Hunt for Red October       781        Paramount   200.5  1990
Valkyrie                       782              MGM   200.3  2008

[782 rows x 4 columns]

In [36]:
df["Gross"].mean()

np.float64(439.0308184143222)

In [41]:
st = df.groupby("Studio")
st["Gross"].sum().sort_values(ascending=False).head()

Studio
Buena Vista        73585.0
Warner Brothers    58643.8
Fox                50420.8
Universal          44302.3
Sony               32822.5
Name: Gross, dtype: float64